# Generated by Django 4.2 on 2023-04-28 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Jobs_Listings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('job_title', models.CharField(max_length=100)),
                ('job_link', models.CharField(max_length=10000)),
                ('deadline', models.CharField(max_length=100)),
            ],
        ),
    ]
